NumberMap
cubik-oss/stringmap-es5 pull request #1
Opened 2017-07-05 11:42 UTC by Rested

All the tests work, not sure if I've set something up a bit wrong though.

2017-07-05 13:10 UTC, timruffles requested changes
Great start! I think there a few changes it makes sense to do? Let me know what you think.

2017-07-05 13:10 UTC, timruffles commented on stringmap.test.ts
> +describe("numbermap", function() {
Did you want to pop the number map tests in here? Would also clean up some of the duplication in the test descriptions (i.e they all start with 'NumberMap')

2017-07-05 13:10 UTC, timruffles commented on stringmap.ts
> +export class NumberMap<V, K extends number = number> {
Shall we pop this in its own file?

2017-07-05 13:10 UTC, timruffles commented on target-typescript/stringmap.d.ts
> +export declare class NumberMap<V, K extends number = number> {
`number` can't be usefully extended as far as I know, so I'd remove the generic from this type and just make `K` number.

2017-07-06 13:58 UTC, timruffles approved these changes
Great! LGTM

2017-07-06 14:21 UTC, Rested commented
hmm think we still need to change the main variable in the package so that it's exporting both. How is it best to structure this? An index.ts file with this:
`import { StringMap } from "./stringmap";
import { NumberMap } from "./numbermap";

export const ES5Map = {
    NumberMap: NumberMap,
    StringMap: StringMap
}`

2017-07-06 15:13 UTC, Rested commented on index.ts
> +export { StringMap } from "./stringmap";
is this the proper way to go do this in ts?

2017-07-07 10:57 UTC, timruffles commented on index.ts
> +export { StringMap } from "./stringmap";
That's great!

2017-07-07 11:09 UTC, merged